# Generated by Django 2.0.1 on 2018-03-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default="Cette page n'est pas encore remplie.")),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usercareer',
            options={'ordering': ['-added_date']},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'ordering': ['-added_date']},
        ),
        migrations.AlterModelOptions(
            name='userpart',
            options={'ordering': ['-added_date']},
        ),
        migrations.AlterModelOptions(
            name='userpath',
            options={'ordering': ['-added_date']},
        ),
        migrations.AddField(
            model_name='usercareer',
            name='added_date',
            field=models.DateTimeField(default='2018-02-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='added_date',
            field=models.DateTimeField(default='2018-02-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='userpart',
            name='added_date',
            field=models.DateTimeField(default='2018-02-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='userpath',
            name='added_date',
            field=models.DateTimeField(default='2018-02-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(default='Aucune description disponible'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='Aucune description disponible'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(default='Aucune description disponible'),
        ),
        migrations.AlterField(
            model_name='path',
            name='description',
            field=models.TextField(default='Aucune description disponible'),
        ),
    ]
