# Generated by Django 2.0.1 on 2018-03-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180321_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='user_path',
        ),
    ]
