# Generated by Django 2.0.1 on 2018-03-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_usercourse_user_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercareer',
            name='career',
        ),
        migrations.RemoveField(
            model_name='usercareer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpart',
            name='part',
        ),
        migrations.RemoveField(
            model_name='userpart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpart',
            name='user_course',
        ),
        migrations.RemoveField(
            model_name='userpath',
            name='path',
        ),
        migrations.RemoveField(
            model_name='userpath',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpath',
            name='user_career',
        ),
        migrations.DeleteModel(
            name='UserCareer',
        ),
        migrations.DeleteModel(
            name='UserPart',
        ),
        migrations.DeleteModel(
            name='UserPath',
        ),
    ]
