# Generated by Django 2.0.1 on 2018-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180326_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='source',
            field=models.TextField(default="Aucune source n'est définie"),
        ),
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.TextField(default="Aucune source n'est définie"),
        ),
        migrations.AddField(
            model_name='part',
            name='source',
            field=models.TextField(default="Aucune source n'est définie"),
        ),
        migrations.AddField(
            model_name='path',
            name='source',
            field=models.TextField(default="Aucune source n'est définie"),
        ),
    ]
